GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' IDENTIFIED BY 'strongpassword';
FLUSH PRIVILEGES;

ALTER USER 'admin'@'%' IDENTIFIED VIA mysql_native_password USING PASSWORD('strongpassword');
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS central_db;
USE central_db;

CREATE TABLE IF NOT EXISTS tenants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    db_name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);